import '../styles/main.scss';
import Hero from '../components/Hero/Hero.js';
const hero = new Hero();
import About from '../components/AboutUs/About.js';
const about = new About();
import Gallery from '../components/Gallery/Gallery.js';
const gallery = new Gallery();
import Reviews from '../components/Reviews/Reviews.js';
const reviews = new Reviews();
import Communication from '../components/Communication/Communication.js';
const communication = new Communication();
import Footer from '../components/footer/Footer.js';
const footer = new Footer();

const app = document.getElementById('app');
app.appendChild(hero.element);
app.appendChild(about.element);
app.appendChild(gallery.element);
app.appendChild(reviews.element);
app.appendChild(communication.element);
app.appendChild(footer.element);